student_is/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('students.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

students/urls.py
from django.urls import path

from . import views

app_name = 'students'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.CreateStudentView.as_view(), name='create'),
    path('<int:pk>/edit/', views.UpdateStudentView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteStudentView.as_view(), name='delete'),
]

students/models.py
from django.db import models

# Create your models here.

GENDERS = [
    ('M', 'Male'),
    ('F', 'Female'),
]


class Student(models.Model):
    first_name = models.CharField(max_length=255, null=False, blank=False)
    middle_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, null=False, blank=False)
    gender = models.CharField(max_length=255, null=False, blank=False)
    contact_number = models.CharField(max_length=15)
    address = models.TextField(blank=False, null=False)
    admit_date = models.DateField(blank=False, null=False)
    course = models.CharField(max_length=255, null=False, blank=False)
    year = models.PositiveSmallIntegerField(null=False, blank=False)
    section = models.PositiveSmallIntegerField(null=False, blank=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name} of {self.course_section}"

    @property
    def course_section(self):
        return f"{self.course} {self.year}-{self.section}"

students/forms.py
from django.forms import ModelForm, widgets
from .models import GENDERS, Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = [
            "first_name",
            "middle_name",
            "last_name",
            "gender",
            "contact_number",
            "address",
            "admit_date",
            "course",
            "year",
            "section",
        ]
        widgets = {
            "gender": widgets.RadioSelect(choices=GENDERS),
            "admit_date": widgets.DateInput(attrs={"type": "date"}),
        }

students/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django import forms
from django.urls import reverse

from students.forms import StudentForm
from students.models import GENDERS, Student

# Create your views here.


class IndexView(ListView):
    model = Student
    context_object_name = "students"


class CreateStudentView(CreateView):
    model = Student
    form_class = StudentForm

    def get_success_url(self):
        return reverse('students:index')


class UpdateStudentView(UpdateView):
    model = Student
    form_class = StudentForm

    def get_success_url(self):
        return reverse('students:index')


class DeleteStudentView(DeleteView):
    model = Student

    def get_success_url(self):
        return reverse('students:index')

students/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Information System</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'styles.css' %}">

</head>

<body>

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'students:index' %}">Student Information System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'students:index' %}">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container py-5">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script>
</body>

</html>

students/templates/students/student_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}

    <p>
        Are you sure you want to delete "{{ object }}"?
    </p>

    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'students:index' %}" class="btn">Cancel</a>
</form>

{% endblock content %}

students/templates/students/student_form.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

students/templates/students/student_list.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'students:create' %}" class="btn btn-primary">Add Student</a>

<table class="table">

    <thead>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Last Name</th>
        <th>Gender</th>
        <th>Contact Number</th>
        <th>Address</th>
        <th>Admission Date</th>
        <th>Course</th>
        <th>Year</th>
        <th>Section</th>
        <th>Actions</th>
    </thead>

    <tbody>
        {% for student in students %}
        <tr>
            <td>{{ student.first_name }}</td>
            <td>{{ student.middle_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.gender }}</td>
            <td>{{ student.contact_number }}</td>
            <td>{{ student.address }}</td>
            <td>{{ student.admit_date }}</td>
            <td>{{ student.course }}</td>
            <td>{{ student.year }}</td>
            <td>{{ student.section }}</td>
            <td>
                <a href="{% url 'students:update' student.pk %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'students:delete' student.pk %}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>


</table>

{% endblock content %}